const labels = {
  en: {
    appName: "DSA & DAA Learning",
    home: "Home",
    topics: "Topics",
    playground: "Playground",
    about: "About",
    dsa: "Data Structures & Algorithms",
    daa: "Design & Analysis of Algorithms",
    run: "Run Code",
    submit: "Submit",
    reset: "Reset",
    hint: "Show Hint",
    solution: "Show Solution",
    next: "Next",
    prev: "Previous",
    problems: "Practice Problems",
    lessons: "Lessons",
    startLearning: "Start Learning",
    totalTopics: "Total Topics",
    totalProblems: "Total Problems",
    languages: "Languages Supported",
    heroTitle: "Master DSA & DAA",
    heroSubtitle: "Learn Data Structures, Algorithms & Design Analysis from beginner to advanced with real-life examples, interactive visualizations, and 1000+ practice problems",
    selectLanguage: "Select Language",
    testCases: "Test Cases",
    passed: "Passed",
    failed: "Failed",
    running: "Running...",
    output: "Output",
    input: "Input",
    expected: "Expected Output",
    yourOutput: "Your Output",
    difficulty: "Difficulty",
    all: "All",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    realLifeExample: "Real Life Example",
    keyPoints: "Key Points",
    timeComplexity: "Time Complexity",
    spaceComplexity: "Space Complexity",
    codeExample: "Code Example",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    progress: "Progress",
  },
  hi: {
    appName: "DSA & DAA Seekho",
    home: "Home",
    topics: "Topics",
    playground: "Code Likho",
    about: "Baare Mein",
    dsa: "Data Structures & Algorithms",
    daa: "Algorithm Ka Design & Analysis",
    run: "Code Chalao",
    submit: "Submit Karo",
    reset: "Reset",
    hint: "Hint Dikhao",
    solution: "Solution Dikhao",
    next: "Agle",
    prev: "Pichle",
    problems: "Practice Problems",
    lessons: "Padhao",
    startLearning: "Seekhna Shuru Karo",
    totalTopics: "Total Topics",
    totalProblems: "Total Problems",
    languages: "Languages Support",
    heroTitle: "DSA & DAA Seekho",
    heroSubtitle: "Data Structures, Algorithms aur Design Analysis seekho beginner se advanced tak - real-life examples, interactive visualizations, aur 1000+ practice problems ke saath",
    selectLanguage: "Language Chuno",
    testCases: "Test Cases",
    passed: "Pass",
    failed: "Fail",
    running: "Chal raha hai...",
    output: "Output",
    input: "Input",
    expected: "Expected Output",
    yourOutput: "Tumhara Output",
    difficulty: "Difficulty",
    all: "Sab",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    realLifeExample: "Real Life Example",
    keyPoints: "Important Points",
    timeComplexity: "Time Complexity",
    spaceComplexity: "Space Complexity",
    codeExample: "Code Example",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    progress: "Progress",
  },
};

export default labels;
